name: Ejemplo de composite

on: [push]

jobs: 
  say-hello: 
    runs-on: ubuntu-latest
    
    env:
      MY_VAR: Mi variable de entorno
    
    steps:
      - name: Test
        env: 
          STEP_MY_VAR: nivel step

        run: |
          echo "Valor $MY_VAR"
          echo "Valor Step $STEP_MY_VAR"
    #steps:
      #Usamos una action desde el market, si dice action es de git si dice usario es de un usuario.  
      # - name: Checkout
      #   uses: actions/checkout@v4.2.1  


      # Usamos un script propio
      # - name: ls
      #   ##con pipe | puedo hacer multilinea
      #   run: | 
      #     chmod +x script.sh
      #     ./script.sh

      # Usamos una action en my-action
      # - name: ls
      #   uses: ./.github/actions/my-action


    #Servicios
    # services: 
    #   mysql:
    #     image: mysql:5.7
    #     env: 
    #       MYSQL_ROOT_PASSWORD: jordi
    #     ports: 
    #       - 3306:3306
    #   redis:
    #     image: redis
    #     ports:
    #       - 6379:6379
