name: Test

on: [push]

jobs: 
  test-build: 
    runs-on: ubuntu-latest
    
    #steps:
      #Usamos una action desde el market, si dice action es de git si dice usario es de un usuario.  
      # - name: Checkout
      #   uses: actions/checkout@v4.2.1  


      # Usamos un script propio
      # - name: ls
      #   ##con pipe | puedo hacer multilinea
      #   run: | 
      #     chmod +x script.sh
      #     ./script.sh

      # Usamos una action en my-action
      # - name: ls
      #   uses: ./.github/actions/my-action


    #Servicios
    services: 
      mysql:
        image: mysql:5.7
        env: 
          MYSQL_ROOT_PASSWORD: jordi
        ports: 
          - 3306:3306

    steps:
      - name: test commit 
        run: ls -la
